# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Scorch's Home Lab
headerStyle: underlined
background:
  image: images/synthwave-01.jpg
  # blur: sm
  brightness: 10
theme: dark
cardBlur: md
hideVersion: false
statusStyle: dot
disableCollapse: true
layout:
  - Information:
      icon: si-googlecalendar.svg
      style: row
      columns: 2
      Calendar:
      Infrastructure:
        style: column
        rows: 3
      Speedtest:
        style: column
        rows: 1
  - Media:
      icon: si-vlcmediaplayer.svg
      style: row
      columns: 4
  - Services:
      icon: si-docker.svg
      style: row
      columns: 4
      useEqualHeights: true
  - Virtual-Machines:
      icon: si-serverless.svg
      style: row
      columns: 4
      Node01:
        style: column
      Node02:
        style: column
      Node03:
        style: column
      Node04:
        style: column
