---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/docker/

docker-node01:
  host: 192.168.1.51
  port: 2375

docker-node02:
  host: 192.168.1.52
  port: 2375

docker-node03:
  host: 192.168.1.53
  port: 2375

docker-node04:
  host: 192.168.1.54
  port: 2375