---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/docker/

# LOCALHOST
docker-node02:
  # socket: /var/run/docker.sock
  host: 192.168.1.52
  port: 2375

docker-node03:
  host: 192.168.1.53
  port: 2375

docker-node04:
  host: 192.168.1.54
  port: 2375