# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Ammar's Home Lab
headerStyle: underlined
background:
  image: images/synthwave-01.jpg
  # blur: sm
  brightness: 10
theme: dark
cardBlur: md
hideVersion: true
statusStyle: dot
disableCollapse: true
layout:
  - Information:
      style: row
      columns: 2
      Calendar:
      Infrastructure:
        style: column
        rows: 3
  - Media:
      style: row
      columns: 4
  - Services:
      style: row
      columns: 4
      useEqualHeights: true
  - Virtual_Machines:
      style: row
      columns: 4
      Node01:
        style: column
      Node02:
        style: column
      Node03:
        style: column
      Node04:
        style: column
