---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services
# Icons: https://simpleicons.org/

- Information:
  - Calendar:
    - Calendar:
        weight: 0
        widget:
          type: calendar
          firstDayInWeek: monday
          view: monthly
          maxEvents: 10
          showTime: true
          timezone: {{ timezone }}
          integrations:
            - type: radarr
              service_group: Media
              service_name: Radarr
              color: orange
            - type: sonarr
              service_group: Media
              service_name: Sonarr
              color: teal
  - Infrastructure:
    - DNS-01:
        weight: 0
        icon: si-nextdns.svg
        server: docker-node01
        container: dns-server
        href: https://dns-node01.{{ domain }}
        widget:
          type: technitium
          url: https://dns-node01.{{ domain }}
          username: admin
          key: {{ dns_api_key }}
          range: LastDay
    - DNS-02:
        weight: 1
        icon: si-nextdns.svg
        server: docker-node02
        container: dns-server
        href: https://dns-node02.{{ domain }}
        widget:
          type: technitium
          url: https://dns-node02.{{ domain }}
          username: admin
          key: {{ dns_api_key }}
          range: LastDay
    - JP-AWK-NAS01:
        weight: 1
        icon: si-proxmox.svg
        href: https://jp-awk-nas01.{{ domain }}:8006
        widget:
          type: proxmox
          url: https://jp-awk-nas01.{{ domain }}:8006
          username: read-only@pam!gethomepage
          password: {{ jp_awk_nas01_token }}
          node: jp-awk-nas01
  - Speedtest:
    - Speedtest:
        weight: 0
        icon: si-speedtest.svg
        server: docker-node01
        container: speedtest
        href: https://speedtest.{{ domain }}
        widget:
          type: speedtest
          url: https://speedtest.{{ domain }}
          version: 1
          bitratePrecision: 3

- Media:
  - Jellyfin:
      weight: 0
      icon: si-jellyfin.svg
      server: docker-node04
      container: jellyfin
      href: http://jellyfin.{{ domain }}
      widget:
        type: jellyfin
        url: http://jellyfin.{{ domain }}
        key: {{ jellyfin_api_key }}
        enableBlocks: true
        enableNowPlaying: true
        enableUser: true
        enableMediaControl: false
        showEpisodeNumber: true
        expandOneStreamToTwoRows: false
  - Seerr:
      weight: 1
      icon: seerr.png
      server: docker-node04
      container: seerr
      href: https://media.{{ domain }}
      widget:
        type: jellyseerr
        url: https://media.{{ domain }}
        key: {{ jellyseerr_api_key }}
  - Gluetun:
      weight: 2
      icon: si-protonvpn.svg
      server: docker-node04
      container: gluetun
      href: https://gluetun.{{ domain }}
      widget:
        type: gluetun
        url: https://gluetun.{{ domain }}
  - Radarr:
      weight: 3
      icon: si-radarr.svg
      server: docker-node04
      container: radarr
      href: https://radarr.{{ domain }}
      widget:
        type: radarr
        url: https://radarr.{{ domain }}
        key: {{ radarr_api_key }}
        enableQueue: true
  - Sonarr:
      weight: 4
      icon: si-sonarr.svg
      server: docker-node04
      container: sonarr
      href: https://sonarr.{{ domain }}
      widget:
        type: sonarr
        url: https://sonarr.{{ domain }}
        key: {{ sonarr_api_key }}
        enableQueue: true
  - Lidarr:
      weight: 5
      icon: lidarr.png
      server: docker-node04
      container: lidarr
      href: https://lidarr.{{ domain }}
      widget:
        type: lidarr
        url: https://lidarr.{{ domain }}
        key: {{ lidarr_api_key }}
  - Prowlarr:
      weight: 6
      icon: prowlarr.png
      server: docker-node04
      container: prowlarr
      href: https://prowlarr.{{ domain }}
      widget:
        type: prowlarr
        url: https://prowlarr.{{ domain }}
        key: {{ prowlarr_api_key }}
  - Bazarr:
      weight: 7
      icon: bazarr.png
      server: docker-node04
      container: bazarr
      href: https://bazarr.{{ domain }}
      widget:
        type: bazarr
        url: https://bazarr.{{ domain }}
        key: {{ bazarr_api_key }}
  - qBittorrent:
      weight: 8
      icon: qbittorrent.png
      server: docker-node04
      container: qbittorrent
      href: https://qbittorrent.{{ domain }}
      widget:
        type: qbittorrent
        url: https://qbittorrent.{{ domain }}
        username: admin
        password: {{ qbittorrent_pass }}
        enableLeechProgress: true
        enableLeechSize: true
  - Pinchflat:
      weight: 9
      icon: si-youtube.svg
      server: docker-node04
      container: pinchflat
      href: https://youtube.{{ domain }}
      showStats: true

- Virtual-Machines:
  - Node01:
    - Traefik:
        weight: 0
        icon: si-traefikproxy.svg
        server: docker-node01
        container: traefik-traefik-1
        href: https://traefik-node01.{{ domain }}
        widget:
          type: traefik
          url: https://traefik-node01.{{ domain }}
          username: admin
          password: {{ traefik_pass }}
    - CPU:
        weight: 1
        icon: si-glance.svg
        server: docker-node01
        container: glances-glances-1
        href: http://glances-node01.{{ domain }}
        widget:
          type: glances
          url: http://glances-node01.{{ domain }}:80
          version: 4
          metric: cpu
    - Memory:
        weight: 2
        icon: si-glance.svg
        server: docker-node01
        container: glances-glances-1
        href: http://glances-node01.{{ domain }}
        widget:
          type: glances
          url: http://glances-node01.{{ domain }}:80
          version: 4
          metric: memory
    - OS_Disk:
        weight: 3
        icon: si-glance.svg
        server: docker-node01
        container: glances-glances-1
        href: http://glances-node01.{{ domain }}
        widget:
          type: glances
          url: http://glances-node01.{{ domain }}:80
          version: 4
          metric: fs:/rootfs

  - Node02:
    - Traefik:
        weight: 0
        icon: si-traefikproxy.svg
        server: docker-node02
        container: traefik-traefik-1
        href: https://traefik-node02.{{ domain }}
        widget:
          type: traefik
          url: https://traefik-node02.{{ domain }}
          username: admin
          password: {{ traefik_pass }}
    - CPU:
        weight: 1
        icon: si-glance.svg
        server: docker-node02
        container: glances-glances-1
        href: http://glances-node02.{{ domain }}
        widget:
          type: glances
          url: http://glances-node02.{{ domain }}:80
          version: 4
          metric: cpu
    - Memory:
        weight: 2
        icon: si-glance.svg
        server: docker-node02
        container: glances-glances-1
        href: http://glances-node02.{{ domain }}
        widget:
          type: glances
          url: http://glances-node02.{{ domain }}:80
          version: 4
          metric: memory
    - OS_Disk:
        weight: 4
        icon: si-glance.svg
        server: docker-node02
        container: glances-glances-1
        href: http://glances-node02.{{ domain }}
        widget:
          type: glances
          url: http://glances-node02.{{ domain }}:80
          version: 4
          metric: fs:/rootfs

  - Node03:
    - Traefik:
        weight: 0
        icon: si-traefikproxy.svg
        server: docker-node03
        container: traefik-traefik-1
        href: https://traefik-node03.{{ domain }}
        widget:
          type: traefik
          url: https://traefik-node03.{{ domain }}
          username: admin
          password: {{ traefik_pass }}
    - CPU:
        weight: 1
        icon: si-glance.svg
        server: docker-node03
        container: glances-glances-1
        href: http://glances-node03.{{ domain }}
        widget:
          type: glances
          url: http://glances-node03.{{ domain }}:80
          version: 4
          metric: cpu
    - Memory:
        weight: 2
        icon: si-glance.svg
        server: docker-node03
        container: glances-glances-1
        href: http://glances-node03.{{ domain }}
        widget:
          type: glances
          url: http://glances-node03.{{ domain }}:80
          version: 4
          metric: memory
    - OS_Disk:
        weight: 3
        icon: si-glance.svg
        server: docker-node03
        container: glances-glances-1
        href: http://glances-node03.{{ domain }}
        widget:
          type: glances
          url: http://glances-node03.{{ domain }}:80
          version: 4
          metric: fs:/rootfs
    - Immich_Disk_0:
        weight: 4
        icon: si-glance.svg
        server: docker-node03
        container: glances-glances-1
        href: http://glances-node03.{{ domain }}
        widget:
          type: glances
          url: http://glances-node03.{{ domain }}:80
          version: 4
          metric: fs:/rootfs/mnt/immich/disk-0
    - Services_Disk_0:
        weight: 5
        icon: si-glance.svg
        server: docker-node03
        container: glances-glances-1
        href: http://glances-node03.{{ domain }}
        widget:
          type: glances
          url: http://glances-node03.{{ domain }}:80
          version: 4
          metric: fs:/rootfs/mnt/services/disk-0

  - Node04:
    - Traefik:
        weight: 0
        icon: si-traefikproxy.svg
        server: docker-node04
        container: traefik-traefik-1
        href: https://traefik-node04.{{ domain }}
        widget:
          type: traefik
          url: https://traefik-node04.{{ domain }}
          username: admin
          password: {{ traefik_pass }}
    - CPU:
        weight: 1
        icon: si-glance.svg
        server: docker-node04
        container: glances-glances-1
        href: http://glances-node04.{{ domain }}
        widget:
          type: glances
          url: http://glances-node04.{{ domain }}:80
          version: 4
          metric: cpu
    - Memory:
        weight: 2
        icon: si-glance.svg
        server: docker-node04
        container: glances-glances-1
        href: http://glances-node04.{{ domain }}
        widget:
          type: glances
          url: http://glances-node04.{{ domain }}:80
          version: 4
          metric: memory
    - OS_Disk:
        weight: 3
        icon: si-glance.svg
        server: docker-node04
        container: glances-glances-1
        href: http://glances-node04.{{ domain }}
        widget:
          type: glances
          url: http://glances-node04.{{ domain }}:80
          version: 4
          metric: fs:/rootfs
    - Media_Disk_0:
        weight: 4
        icon: si-glance.svg
        server: docker-node04
        container: glances-glances-1
        href: http://glances-node04.{{ domain }}
        widget:
          type: glances
          url: http://glances-node04.{{ domain }}:80
          version: 4
          metric: fs:/rootfs/mnt/media/disk-0
    - Media_Disk_1:
        weight: 5
        icon: si-glance.svg
        server: docker-node04
        container: glances-glances-1
        href: http://glances-node04.{{ domain }}
        widget:
          type: glances
          url: http://glances-node04.{{ domain }}:80
          version: 4
          metric: fs:/rootfs/mnt/media/disk-1

- Services:
  - Immich:
      weight: 0
      icon: si-immich.svg
      server: docker-node03
      container: immich_server
      href: https://immich.{{ domain }}
      widget:
        type: immich
        url: https://immich.{{ domain }}
        key: {{ immich_api_key }}
        version: 2
  - Vaultwarden:
      weight: 50
      icon: si-vaultwarden.svg
      server: docker-node02
      container: vaultwarden-vaultwarden-1
      href: https://vault.{{ domain }}
      showStats: true
  - GetHomePage:
      weight: 51
      icon: si-homepage.svg
      server: docker-node02
      container: gethomepage-homepage-1
      href: https://home.{{ domain }}
      showStats: true
  - qUI:
      weight: 52
      icon: si-qbittorrent.svg
      server: docker-node04
      container: qui
      href: https://qui.{{ domain }}
      showStats: true
  - Paperless-ngx:
      weight: 53
      icon: si-paperlessngx.svg
      server: docker-node03
      container: paperless-paperless-1
      href: https://paperless.{{ domain }}
      widget:
        type: paperlessngx
        url: https://paperless.{{ domain }}:443
        key: {{ paperless_api_key }}
  - Nextcloud:
      weight: 54
      icon: si-nextcloud.svg
      server: docker-node03
      container: nextcloud-nextcloud-1
      href: https://nextcloud.{{ domain }}
      widget:
        type: nextcloud
        url: https://nextcloud.{{ domain }}
        username: {{ nextcloud_username }}
        password: {{ nextcloud_password }}
  - Bento:
      weight: 55
      icon: mdi-file-pdf-box.svg
      server: docker-node03
      container: bentopdf
      href: https://bento-pdf.{{ domain }}
      showStats: true
