nextcloud_db_root_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38626231393333643363323331366638333333353938366262346232656365656631646330396135
          3232316362663232373731653964653435383665666137310a666266326330346632636233363230
          34643461626430663563363130663263633037303263386265383632656662343939316466326666
          3431623335353332330a666361623737626139333934623739313231633665353732363636366361
          34636434643165626430616434396365646364613033646664336366383362616566383132343763
          3363323731646139623864613338303831313066653562613261

nextcloud_db_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30613435613866613864306234643639373436363864666237656364336439303331356433383330
          3631663439336331323231656236373437303938333139320a343137306265353339326463313035
          30623337363630333136623562613439656266396561386333343235623766326264366565366532
          6436393734356637390a313830663134336464626437663839633339333661333034346630663238
          34323130633462326437373764376166373238353733376663356138313434636538376132343663
          6363383834636436326436343536313863613362303034383238

nextcloud_username: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38343136306531623136363863313965343666303934333962346638383662616230653835336565
          3362613735663639366361366438376565643437616265630a303239353831613632376666646165
          66633331643630303939396238383337616133623039666162626264653133336566636633336562
          6563356565383731350a333863353834373834336138323135313665313636633934303335363639
          3436

nextcloud_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62303333633632393237376537623339343766373035373566643661343937303762356536643466
          3165353231333366656437393335373836656337373336610a326131666665316166643362623431
          30393333626261363635333636663039313261373433333130323237386661393461326431663962
          3734353133326131630a336536343839616666663963363561643461353961353633643934663863
          3532