gluetun_wireguard_public_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31656661353066373364346437396463306162303834643432363563353866336661393836666466
          3830653632323138613237343738373336636133613064620a383261626330393966333736363734
          35613664393461343635396463663739393763613461643039373237313162326535633337386662
          3032376137366332640a653763323339663539323764353966343766306162386235656436323063
          38636165613630616334666233656263383737633563633436343735376639373063623362373835
          6639346232326530346136356130663066333761373532343131

gluetun_wireguard_private_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66613930366562616137653734373537303836313963323332623130626231303832666562326231
          6531623835326361313537313738643633626233346565390a343866613133626439613864393262
          33343535383662366461336137393937666634323763373732363130643234373463656432346163
          3461383631353133380a613535343835373263623535663633633034616531343232373039316433
          63333135343565323564363263623738376437656264333835373331356261393262623663376266
          3362653537613730633063623864636561363865666463343134

gluetun_wireguard_addresses: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35333435323163326536303437653261303332323934643639343732613030363263383136353362
          3338623339626661346137323463383137313965646464340a376365653666653763386534366534
          64306362363539623234346235363534656164616630386166393166613034663236303265356338
          3335643339323035360a663061616165616661616233646163613263306334346330366432386438
          3239

gluetun_wireguard_endpoint_ip: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35616139313437343533656630653764363834346537393363373461613864646535366361306638
          6264316165643463323262653530626562383661623065380a663863636461313131306431613136
          65383562663539323162306239333137616266376663343333363630643936346163396331303136
          3162656633653835350a646565313365303739326363633863383263663830313733656464663239
          6330

gluetun_wireguard_endpoint_port: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32653139613837333836333665353363353136623666363630646432323635393337333464303939
          3536373731383462386562306631613131383738613964640a306632646465373331623231386133
          39623236633161386263373035333136353537613364343432373636386533626465366138646163
          3637613336623531330a613239303239376132313735373037396636333835616365333439323464
          3933

jellyfin_api_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38376530316665623436633961326164616563366566323337643237616132663963353235333865
          6264626534313465633863636463346532376632656364630a323931353539363966616366313861
          32663037613930633836353433376161393033643633663535623763613636626134646531663731
          3964306533333965660a613635393966353066616235613132653636643535643164653166663030
          39393030663837343239316531666137393431373439343230393936623831366662643963373735
          3733346237333361303637396637623466656163656637346666

jellyseerr_api_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          62646365636436303338656630616138396637633365616366353335383138336562363965393535
          3938376565333139363131323436353633356337613266620a393038643963393631316263326461
          61623865613839353930333763656232643865336164653966376664626333643537326663356336
          3734386331353764660a363034396539366631396339303261326530626162613236376364356263
          31313830616635373462656230663438663363393631346435386332323166326530346331663566
          38373038316432663462333862326337356633376135323265613033396231333431346561623765
          62396662616133323964306330383139386632303666373434356635313237613733363932666461
          34343439346262663232

radarr_api_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64643439313736313664393535376632303236343065346638316164646462333037383035366633
          3564333064626338333531356136303735353838636565610a386637343835633339323964646338
          64353664313231313536633861376639373534653930313366626262656238343636373539326235
          6236633439633933660a646636623035386139613030343264333763616463383437633536663262
          63373536666232326262353538633638653666636266663539336233363761623736653664666366
          3861343761393839633365303063333862333330353838653565

sonarr_api_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30636665613430356366636636353338323130303439363633313037383839333630613163336163
          6163343034633266353565396532363838663533313237360a623233653938376531623933363237
          66626132393733346332623566393366643331613461316232363861306263666436623966336332
          3539306162356237340a383033373966653566666261366461323636313930333966643466383136
          38366538306534303537366430633163343630316537333639616661366533383334393737643534
          6338323336336134633863623632333163623666646566666261

prowlarr_api_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33323032386430313361353161396262643065616661383562333035326363353561353761353266
          6137633263646566396332633662346335316539313835620a383034323864646662363137663439
          64333135313739306233653536653639623965633534343366623364303865396265616538353561
          6331626362613161320a666232663135343862316631396165633237653338313035306333613439
          38313439613332373031363966646366393666303262613461343533353636383432616131323637
          6638616562333530383937343939366433366130366531373438

bazarr_api_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64393066613963333533386130336337623564316533646166363934663263623732316537356336
          6166376334616536653735353662396431323133326165620a666236343137363165643433333661
          61303861656237313032373461356538643930663964356234373637393263363133656431643066
          3336643335316131640a636130356435643364356165343430313033393837386635653930623561
          33663638376562353562346166376165386435346235666231393533356537373432333033333034
          3862633234353136336361643239633231396466633232356464

qbittorrent_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66643732393438613934666161623065616432356537633233336539303639356232386433643862
          3838633466363738393265323530636661323230636563370a643135343838653038323065636532
          33643532626531333566373830373435316531646463373066323338383439383466393861623030
          3036363631666537330a643266353430646534313263643662623566376137326633656532346362
          6132