gluetun_wireguard_public_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31656661353066373364346437396463306162303834643432363563353866336661393836666466
          3830653632323138613237343738373336636133613064620a383261626330393966333736363734
          35613664393461343635396463663739393763613461643039373237313162326535633337386662
          3032376137366332640a653763323339663539323764353966343766306162386235656436323063
          38636165613630616334666233656263383737633563633436343735376639373063623362373835
          6639346232326530346136356130663066333761373532343131

gluetun_wireguard_private_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66613930366562616137653734373537303836313963323332623130626231303832666562326231
          6531623835326361313537313738643633626233346565390a343866613133626439613864393262
          33343535383662366461336137393937666634323763373732363130643234373463656432346163
          3461383631353133380a613535343835373263623535663633633034616531343232373039316433
          63333135343565323564363263623738376437656264333835373331356261393262623663376266
          3362653537613730633063623864636561363865666463343134

gluetun_wireguard_addresses: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35333435323163326536303437653261303332323934643639343732613030363263383136353362
          3338623339626661346137323463383137313965646464340a376365653666653763386534366534
          64306362363539623234346235363534656164616630386166393166613034663236303265356338
          3335643339323035360a663061616165616661616233646163613263306334346330366432386438
          3239

gluetun_wireguard_endpoint_ip: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35616139313437343533656630653764363834346537393363373461613864646535366361306638
          6264316165643463323262653530626562383661623065380a663863636461313131306431613136
          65383562663539323162306239333137616266376663343333363630643936346163396331303136
          3162656633653835350a646565313365303739326363633863383263663830313733656464663239
          6330

gluetun_wireguard_endpoint_port: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32653139613837333836333665353363353136623666363630646432323635393337333464303939
          3536373731383462386562306631613131383738613964640a306632646465373331623231386133
          39623236633161386263373035333136353537613364343432373636386533626465366138646163
          3637613336623531330a613239303239376132313735373037396636333835616365333439323464
          3933