dns1: 192.168.1.51
dns2: 192.168.1.52
dns3: 192.168.1.1

dns_domain: scorch.awk
dns_search: scorch.awk scorch.com
dns_search_netplan: "scorch.awk scorch.com"

dns_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64626231363062346562393161663434313231346366393161646264376534633664343466323435
          6162383830613834363365643162356237643861366538300a333563636363333133393937386235
          34376232313964303430353336343465643765333738323233643661643565336438653739323561
          3863386536326561320a353632383561353431633537666566363764663439613935333733376534
          3238

dns_api_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38656566366634656534393533396437373039333531656132613065643036346332646331383761
          6138656135643831613339343938633735656361623231310a636633316439363564356636656537
          35623834396464306661656230373135313838323463623765316239623662396631336533353466
          3662363637616235350a613562643035346634336435653238303434376334373635343364323164
          62313439366232643434626231613862373530323339623232386164323332393464666562303836
          63326338393630646630653232666561303138393064333537633636633138393761316435356662
          34646530303336626239343131396132333563616538633932383764303833663630326236336432
          30313264636362373533
