traefik_auth: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31386232343763326461663339636466376633376161353237633038666566643362306362326363
          3861663134646232663038363165313237303838623432640a646361313339646333396465643830
          35613264393261303236633930653263363433643031373139653031306437343637366662663031
          3134333563616239380a623766636163343261306630666637336239623633316234386539393136
          62336633656635383761366539633562623136643933326661613963343265373639316465653863
          6432363466323835353665363136373232393666653039366330

traefik_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66663035336135313264366235366565303938363937333439646430366638623832316234643239
          3839323931386332346266336539303032363037303364360a633133663533336466373932333131
          65376331303766363733316461663038633265383834373131613432313364383735316633623832
          3037343066366131370a663061306435313431633432383639326639396337333336353139623430
          6265
