passbolt_db_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39376162663561306437663963373539346361386365616339646661306139393033656636373032
          3634616531623832343234646234333564633235366563640a376166626465313466363837303133
          62343637316136303631386330336533623035326639623830663638393562613965653339313431
          3735663861373035620a333035666262316234393063353036356363373733616264613963333866
          6132
