immich_db_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33643963386439333663393664373135333939303163656136636537346634316335303764643336
          6364613231666435663632373965633566643839636162610a393037326637353263656566323935
          33633931636135326132316131643238653235313834363338366665383031383833656135653537
          3731666165656432370a326532336339376131656265653366613662316136636639313466373330
          62633032373762663837613738656666613866396438303365356665386131393165653436353731
          65623334653638356439383563613065313231303036636362646530353232666538363562353434
          613635393637393336613235323131326237
