dns1: 192.168.1.149
dns2: 192.168.1.1
dns3: 192.168.1.52

dns_domain: scorch.awk
dns_search: scorch.awk scorch.com
dns_search_netplan: "scorch.awk scorch.com"

adguard_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64626231363062346562393161663434313231346366393161646264376534633664343466323435
          6162383830613834363365643162356237643861366538300a333563636363333133393937386235
          34376232313964303430353336343465643765333738323233643661643565336438653739323561
          3863386536326561320a353632383561353431633537666566363764663439613935333733376534
          3238