vault_admin_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39353939666431613165633763323162316430613033363836346462323962643962626439646464
          3134383066353463306531333636663461316463383536380a613930386631626631613533313964
          32383364303630376461636162323436343061633966653664366530643264323063653839646638
          3961353739636163320a376665333733626636663435393036643861313437383664306632623735
          33306331663635303530303134323935393033366236636133323231613338623963333233613432
          61303666316563653430333739363863623463326136353331313532643361633562323832653532
          353161356632343033373364666363303565
