paperless_secret_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33336432613932613637396363326439303231313534316266613035643733343537653832356134
          3434643831656235346233616564396131663434346231300a623061343331303633643337356231
          37393537626337663037306466376463623464333038633438363462663938656461653038316436
          3466333233373438320a386634366133346437383731663834653236373533663063323732356565
          31663635646532633137353636643939656661303331343261643837326338366463613137643536
          66363035646334633463396636313034623465346631393534633731386361653039313338373365
          39666231623833363935316133656434326361303237346238613230353965346531623237393531
          30333939316333666633

paperless_api_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39316434653866336631643136613734346433336438633937363763343330323262643535323932
          3533616564626164353636663063656663633531386561310a396361373962666564356661383935
          37643238373837653562326130346433303736326631316562653333653732616235356566663337
          3932333764623131340a353965356332383663663138363831653135326437306262616564383162
          61663864393863313866663931643137633365353332356265666661393536333966366632333161
          3035343465653830656163623963633636363332616239373831