domain: scorch.awk

console_timeout: 28800 # 8 hours
timezone: "Asia/Tokyo"
ssh_port: 22

apt_key_path: /usr/share/keyrings
apt_sources_path: /etc/apt/sources.list.d/

default_email: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37346435366139306530343433633036666333656539313830316463303930366134343664623533
          3665386362346665363032383632626532643862353636320a373064623631353737376162396432
          33613866323838623664333336346137366134643038303764393737313561393233353530633936
          3933616330353635630a643437363638363336653436323635336137656666633062623637363636
          61636230383839616266636161626334396337333831326635303431646431346439
