step_fingerprint: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          38643236393934626464306461363665396563636538343364326331633063393566353334623636
          6632386461333634646564376633616561656561303162380a353538656135326331613238373261
          32316239346639656661393263653664633435393038616261396635616236366432653130313837
          3462616533633831630a613432306532383732346539666433353861666662343335616134356334
          39643239393536323037646232643532646531343265383336666134663662656336623332623030
          35653138343939303235613030343064376336363162656233333033376337323065663461653136
          36363237636538356265393537666238373931333136626262366338376531393934306664616665
          64313136616434613165

step_ca_url: "https://jp-awk-node01.scorch.awk:8443"
