vpn_provider: protonvpn
vpn_user: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61613531366630326466313463366531666437386337356663643432623332653435643262373034
          6162356430376137656639653536353762663233613639660a336463616532663138373531316333
          31326233643439373338623261303566636439313264326664313032346532643533363939386634
          3036313165313135360a643064336565333730363361653864373237323034366464363663353831
          65316533323366333336626638386138313630343732663761373366623465653065
vpn_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32636238626235383665663137323631636135306231633364336263346163393633306335363561
          3739396334353661313934323636656162613533313433360a333064623365626162386662613638
          32373937636463376434653433346566613466663166336539303634363938313966326330656630
          6664383038633132640a333066633731643733343165613361326233396439643661626466616237
          36613661613837316165303762333464643262393432666561343634373639633362653634316234
          3031313263333735396661326639316365346535343664636561
vpn_countries: Singapore
