setup_tailscale: true

ts_expire: "2026-03-26"
ts_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65353564393362316564643535323038396234323334633062366562646338636564366532623964
          3761616562626533376338303231653164653936656234630a333863613161646463336133656334
          66333464316366646465653737656636306430333865313134636565353330626334326161646561
          6236336562393630330a343931653438613033653564663030376433303761326538376238303632
          39653265353138626663666239356539383432653439333331363066633435396163656239646231
          36303632376132343166633034646162366462363830356436303664633634376566656639303632
          336133343433633937306531643666333634

ts_expose_subnet: false
