---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

#- Media:
#
- Infrastructure:
  - Node02:
      icon: mdi-server
      server: my-docker
      container: homepage
