- name: Docker Install | Add Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    dest: /usr/share/keyrings/docker.gpg
    mode: '0644'
  when:
    - ansible_facts["distribution"] == "Debian"

- name: Docker Install | Add Docker Repository (deb822 style)
  ansible.builtin.deb822_repository:
    name: docker
    types: [deb]
    uris: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
    signed_by: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    suites: ["{{ ansible_distribution_release | lower }}"]
    components: [stable]
    state: present
    enabled: true
  when:
    - ansible_facts["distribution"] == "Debian"

- name: Docker Install | Install Required Packages
  ansible.builtin.apt:
    name:
      - python3-pip
      - python3-docker
      - docker-ce
      - docker-ce-cli
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Docker Install | Create Symbolic link for Docker Compose V2
  ansible.builtin.file:
    src: /usr/libexec/docker/cli-plugins/docker-compose
    dest: /usr/local/bin/docker-compose
    state: link

- name: Docker Install | Copy daemon.json
  ansible.builtin.template:
    src: "files/docker/expose_daemon.json"
    dest: "/etc/docker/daemon.json"
    mode: '0644'
    owner: root
    group: root
  register: copy_docker_daemon

- name: Docker Install | Ensure /etc/systemd/system/docker.service.d/ exists
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d/
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Docker Install | Copy docker_override.conf
  ansible.builtin.template:
    src: "files/docker/docker_override.conf"
    dest: "/etc/systemd/system/docker.service.d/docker_override.conf"
    mode: '0644'
    owner: root
    group: root
  register: copy_docker_override

- name: Docker Install | Restart Docker Service
  ansible.builtin.systemd:
    name: docker
    state: restarted
    daemon_reload: true
  when: copy_docker_daemon.changed or copy_docker_override.changed
