- name: 00_docker.yml
  ansible.builtin.include_tasks: "00_docker.yml"

- name: 01_traefik.yml
  ansible.builtin.include_tasks: "01_traefik.yml"
  when: application_target == "traefik"

- name: 02_immich.yml
  ansible.builtin.include_tasks: "02_immich.yml"
  when: application_target == "immich"

- name: XX_docker_deploy.yml
  ansible.builtin.include_tasks: "xx_docker_deploy.yml"

- name: Homepage Configuration
  ansible.builtin.include_tasks: "homepage_config.yml"
  when: application_target == "homepage"
