services:
  vaultwarden:
    image: vaultwarden/server:latest
    restart: unless-stopped
    environment:
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "false"
      ADMIN_TOKEN: "{{ vault_admin_token }}"
      DOMAIN: "https://vault.{{ domain }}"
      TZ: "{{ timezone }}"  
    volumes:
      - ./vw-data:/data
    labels:
      # Traefik
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.vault.rule=Host(`vault.{{ domain }}`)"
      - "traefik.http.routers.vault.entrypoints=websecure"
      - "traefik.http.routers.vault.tls=true"
      - "traefik.http.routers.vault.tls.certresolver=stepca"
      - "traefik.http.services.vault.loadbalancer.server.port=80"
    networks:
      - proxy
    
networks:
  proxy:
    external: true