mount_name: immich
mount_drive:
  - scsi-0QEMU_QEMU_HARDDISK_drive-scsi1

additional_packages:
  # GPU drivers and VAAPI
  - firmware-amd-graphics
  - mesa-utils
  - mesa-va-drivers
  - vainfo
  - libva2
  - mesa-vulkan-drivers
  - clinfo
  # Useful utilities
  - cmake
  - python3-dev
  - python3-pip
